/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
        public static final int solid_blue=0x7f020001;
    }
    public static final class id {
        public static final int buttonRow0=0x7f060001;
        public static final int buttonRow1=0x7f060002;
        public static final int buttonRow2=0x7f060003;
        public static final int cellTable=0x7f060000;
        public static final int positionMatchButton=0x7f060004;
        public static final int positionSucessTextField=0x7f060005;
        public static final int soundMatchButton=0x7f060006;
        public static final int soundSucessTextField=0x7f060007;
    }
    public static final class layout {
        public static final int positronic=0x7f030000;
    }
    public static final class raw {
        public static final int c=0x7f040000;
        public static final int h=0x7f040001;
        public static final int k=0x7f040002;
        public static final int l=0x7f040003;
        public static final int q=0x7f040004;
        public static final int r=0x7f040005;
        public static final int s=0x7f040006;
        public static final int t=0x7f040007;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
}
